// ignore_for_file: type=lint
// Generated by `flutterfire configure` for the wird-dev Firebase project.
// This app is registered under com.afnan.wird.dev (the dev flavor's
// applicationId) - the public/prod flavor never links against a Firebase
// project at all, since FeatureFlags.friendsEnabled compiles to false there
// and lib/main.dart never calls Firebase.initializeApp() in that build.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name} - '
          'run `flutterfire configure` again to add that platform.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'AIzaSyD6zrM7Zs9eZ4_pgXwEZ1X-k1HJHP38Ev0',
    appId: '1:327002593542:android:17bc43cee3f10beeb36687',
    messagingSenderId: '327002593542',
    projectId: 'wird-dev',
    storageBucket: 'wird-dev.firebasestorage.app',
  );
}
